# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCT01EnviarMensagem():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cT01EnviarMensagem(self):
    self.driver.get("https://inoveteste.com.br/")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.CSS_SELECTOR, "#nav-menu-item-5643 .item_text").click()
    elements = self.driver.find_elements(By.NAME, "nome")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "assunto")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.NAME, "mensagem")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) .wpcf7-form-control").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".nome > .wpcf7-not-valid-tip").text == "Por favor, preencha o campo obrigatório."
    assert self.driver.find_element(By.CSS_SELECTOR, ".email > .wpcf7-not-valid-tip").text == "Por favor, preencha o campo obrigatório."
    assert self.driver.find_element(By.CSS_SELECTOR, ".assunto > .wpcf7-not-valid-tip").text == "Por favor, preencha o campo obrigatório."
    assert self.driver.find_element(By.CSS_SELECTOR, ".mensagem > .wpcf7-not-valid-tip").text == "Por favor, preencha o campo obrigatório."
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".wpcf7-response-output:nth-child(6)")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "nome").click()
    self.driver.find_element(By.NAME, "nome").send_keys("Iranilson")
    self.driver.find_element(By.NAME, "email").send_keys("irannery@gmail.com")
    self.driver.find_element(By.NAME, "assunto").send_keys("Testando seu curso")
    self.driver.find_element(By.NAME, "mensagem").click()
    self.driver.find_element(By.NAME, "mensagem").send_keys("To testando seu curso na Udemy - Deu certo =D")
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(5) .wpcf7-form-control").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".wpcf7-response-output:nth-child(6)").text == "Sua mensagem foi enviada com sucesso. Obrigado."
  
